apiVersion: v1
kind: Service
metadata:
  name: signoz-frontend
  namespace: platform
spec:
  selector:
    app: signoz-frontend
  ports:
    - name: http
      port: 3301
      targetPort: 3301
  type: ClusterIP
